### ISSUE TITLE
Options to include non-supported keys

### ISSUE THREAD

**Issue by chinyeungli** [nexB/aboutcode-toolkit#108]
we should not have to worry about unknown keys AND

from CSV to About: include any non standard key based on a command line flag
from about to CSV: always include any non standard key (eventually with a warning)

We will need to refine that and the way errors are reported too

**Comment by DennisClark** [comment]
Let's consider providing the ability to identify non-supported keys (custom fields) 
in the MAPPING.CONFIG file 
and then
enhancing genabout to look for those fields in the input .csv going from CSV to ABOUT
and write the extra fields to each ABOUT file 

Going from ABOUT to CSV, I think the idea to include any non-standard key is a good one, and I don't think a warning is needed.

**Comment by DennisClark** [comment]
To expand on the previous comment, add another grouping in MAPPING.CONFIG that would look something like this (without the " characters): 

" # Custom Fields
confirmed_license
attribution_type
modified"

This is just an example of course, but I think it is probably ok to include in the standard MAPPING.CONFIG file -- if the input csv does not have these columns, then they would just be ignored.

**Comment by chinyeungli** [comment]
For the custom field, I propose we should use the same  format as the key mapping.
i.e

#Custom Fields
confirmed_license: Confirmed License
attribution_type: Attribution Type
modified: Modified

**Comment by DennisClark** [comment]
I agree with Chin Yeung's proposal for the Custom Fields format.
