### ISSUE TITLE
Terminal session ends after an error in input commands

### ISSUE THREAD

**Issue by jdaguil** [nexB/aboutcode-toolkit#156]
When trying:

```
python genabout.py ~/tmp/input.csv ~/tmp/
```

I get the following message:

```
Required keys not found.
('name', 'version', 'about_file')
Use the '--mapping' option to map the input keys and verify the mapping information are correct.
OR correct the header keys from the input CSV.

[Process completed]
```

My session is killed and I have to open a new terminal, rerun configure, and rerun the command.

**Comment by jdaguil** [comment]
this was with v1.0.0

**Comment by chinyeungli** [comment]
The exit code is 
sys.exit(errno.EINVAL)

It shouldn't cause any error. Let me do some researches

**Comment by pombredanne** [comment]
@jdaguil which OS and Python version do you use?

**Comment by jdaguil** [comment]
@pombredanne I use the following
Python 2.7.6 
Mac OS 10.9.4

**Comment by pombredanne** [comment]
@jdaguil Could you try with get the latest 2.7 from Python.org?
https://www.python.org/ftp/python/2.7.8/python-2.7.8-macosx10.6.dmg

**Comment by jdaguil** [comment]
@pombredanne I downloaded and ran it with 2.7.8 and it worked without issue for genabout.py but when I ran

```
python genattrib.py
```

so that i could see the syntax it shows the syntax and options but kills the session and shows  [Process Completed] again. See below:

```
Path for input, output and component list are required.

Usage: genattrib.py [options] input_path output_path component_list

    Input can be a file or directory.
    Output of rendered template must be a file (e.g. .html).
    Component List must be a .csv file which has at least an "about_file" column.


Options:
  -h, --help            Display help
  -v, --version         Display current version, license notice, and copyright notice
  --overwrite           Overwrites the output file if it exists
  --verbosity=VERBOSITY
                        Print more or fewer verbose messages while processing ABOUT files
                        0 - Do not print any warning or error messages, just a total count (default)
                        1 - Print error messages
                        2 - Print error and warning messages

  --template_location=TEMPLATE_LOCATION
                        Use the custom template for the Attribution Generation

  --mapping             Configure the mapping key from the MAPPING.CONFIG


[Process completed]
```

**Comment by jdaguil** [comment]
@pombredanne @chinyeungli 
I ran 

```
python genattrib.py -h
```

instead of 

```
python genattrib.py
```

and i no longer have the [Process Completed] issue

**Comment by chinyeungli** [comment]
@pombredanne I am not sure what can I do here. I suspect this is something related to the OS or Python. What's your take?

**Comment by pombredanne** [comment]
I cannot reproduce the issue on Windows
But I can on Linux and Cygwin.
After a configure using a tab in shell kills the process. This is likely a virtualenv issue... digging
