### ISSUE TITLE
generate ABOUT files from a CSV

### ISSUE THREAD

**Issue by chinyeungli** [nexB/aboutcode-toolkit#2]
user should be able to generate ABOUT files from a CSV as an input

Current proposals: 

A. An interactive prompt. 

For instance, user only needs to type 

python about.py
Then the script will prompt:
1. Collect ABOUT files context
2. Generate ABOUT files
3. Exit
   Select: 
   something like the above, and the ask for input/output and all kind of options.

B. Create another script, maybe, called generate_about_file.py

**Comment by pombredanne** [comment]
@chinyeungli what are the benefits of the interactive prompt? IMHO another script would be simpler

**Comment by pombredanne** [comment]
what about calling genabout.py?

**Comment by chinyeungli** [comment]
B: Create another script - genabout.py is the winner

First pass: Create about files (Assuming the about file doesn't exist.)

Second pass: "Update" the about file (i.e. don't overwrite the about file if it already exists)

**Comment by chinyeungli** [comment]
In addition, the generated about file is lied side by side with the code and not in a specific output directory.

**Comment by chinyeungli** [comment]
My propose syntax:
python genabout.py [input csv]

**Comment by chinyeungli** [comment]
@pombredanne what should be version number for this script? should it be the same version as the about.py?

**Comment by chinyeungli** [comment]
creates the basic genabout.py

https://github.com/dejacode/about-code-tool/blob/master/genabout.py

others needed features/enhancements/code improvement will be broken down
