### ISSUE TITLE
Setup travis CI for tests

### ISSUE THREAD

**Issue by pombredanne** [nexB/aboutcode-toolkit#21]

**Comment by tdruez** [comment]
http://about.travis-ci.org/docs/user/languages/python/

**Comment by tdruez** [comment]
Enabled Travis as explained in http://about.travis-ci.org/docs/user/getting-started/

**Comment by tdruez** [comment]
See https://travis-ci.org/profile/dejacode

**Comment by tdruez** [comment]
tests.py will now be executed for python2.6 and python2.7 on each commit.

The results are available at https://travis-ci.org/dejacode/about-code-tool
