### ISSUE TITLE
Extract license text from a license_url

### ISSUE THREAD

**Issue by chinyeungli** [nexB/aboutcode-toolkit#46]
The tool should be able to extract the license text based on the user license_url provided in the ABOUT file and save the license text in the user specific directory.

**Comment by pombredanne** [comment]
@chinyeungli 
What would be the use case for this? 
What if there is no network connection or the website is down? 
What if the license url is an html page as opposed to plain text?
What if the license url points to a page that contains several things among which is the license?

**Comment by mjherzog** [comment]
The specific use case is to get license text from DejaCode, OSI or similar website. There needs to be validation that we get expected results for license text or return an error.

**Comment by chinyeungli** [comment]
The new api call is referenced in #59
