### ISSUE TITLE
Adapt with the latest skeleton

### ISSUE THREAD

**Issue by chinyeungli** [nexB/aboutcode-toolkit#465]
We should adopt the latest code skeleton  structure (https://github.com/nexB/skeleton).

**Comment by chinyeungli** [comment]
The latest merge give the following errors when running the `pytest`
```
tmp/lib/python3.6/site-packages/_pytest/runner.py:311: in from_call
    result: Optional[TResult] = func()
tmp/lib/python3.6/site-packages/_pytest/runner.py:341: in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
tmp/lib/python3.6/site-packages/_pytest/doctest.py:532: in collect
    module = import_path(self.fspath)
tmp/lib/python3.6/site-packages/_pytest/pathlib.py:544: in import_path
    raise ImportPathMismatchError(module_name, module_file, path)
E   _pytest.pathlib.ImportPathMismatchError: ('virtualenv', '/mnt/c/Users/thoma/git/aboutcode-toolkit/tests/testdata/test_gen/inventory/complex/about/virtualenv.py', PosixPath('/mnt/c/Users/thoma/git/aboutcode-toolkit/tests/testdata/test_model/inventory/complex/about/virtualenv.py'))
_____________________________________________________________________________________ ERROR collecting tests/testdata/test_model/inventory/complex/about/virtualenv.py ______________________________________________________________________________________
import file mismatch:
imported module 'virtualenv' has this __file__ attribute:
  /mnt/c/Users/thoma/git/aboutcode-toolkit/tests/testdata/test_gen/inventory/complex/about/virtualenv.py
which is not the same as the test file we want to collect:
  /mnt/c/Users/thoma/git/aboutcode-toolkit/tests/testdata/test_model/inventory/complex/about/virtualenv.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
```

**Comment by chinyeungli** [comment]
@pombredanne @tdruez 
the above error ONLY exists when I use the new configuration scripts which I am testing in https://github.com/nexB/aboutcode-toolkit/tree/465_merge_skeleton
(I tried to do some renaming and clear the .pyc, but then other errors pop up)
I've updated the setup.cfg (https://github.com/nexB/aboutcode-toolkit/blob/465_merge_skeleton/setup.cfg) so that it matches with the all the packages installed in the develop branch (https://github.com/nexB/aboutcode-toolkit/blob/develop/etc/conf/base.txt , https://github.com/nexB/aboutcode-toolkit/blob/develop/etc/conf/dev/base.txt , https://github.com/nexB/aboutcode-toolkit/tree/develop/thirdparty )
However, it is still giving me errors that don't prompts in the develop branch...
I don't know what's the problem and a little help is greatly appreciated

**Comment by tdruez** [comment]
@chinyeungli I'm not familiar with the skeleton and `source configure` is not working on macOS, it actually close the shell tab.

Making the install manually though, I end up with the same issue as you but I do not know how to solve it.

@pombredanne seems to have a solution.

**Comment by chinyeungli** [comment]
Thanks for trying. I will keep digging

**Comment by chinyeungli** [comment]
I've pushed some new code and created a pull request on the skeleton. Will come back to this once the pull request is granted or commented.

**Comment by chinyeungli** [comment]
Fixed in https://github.com/nexB/aboutcode-toolkit/commit/a261885c2a07fc0dd2630e5ec411863abaf46931
