### ISSUE TITLE
Update python requirement to 3.6.2 or above

### ISSUE THREAD

**Issue by chinyeungli** [nexB/aboutcode-toolkit#466]
I was using python 3.6.0 and have this following error `AttributeError: module 'typing' has no attribute 'NoReturn'` when running tests related to Jinja2
I found a similar problem here: https://stackoverflow.com/questions/67569038/attributeerror-module-typing-has-no-attribute-noreturn/67857937#67857937 which suggests to use python 3.6.2 or above.

**Comment by amittri1025** [comment]
How to contribute / solve this issue.. help

**Comment by chinyeungli** [comment]
I think we just need to update the documentation in the README to use python3.6.2 or above and possibly do some checking in the configure scripts

**Comment by Naveen-singla** [comment]
@chinyeungli I would like to resolve this issue by making changes in readme documentation can you please assign this task to me
