### ISSUE TITLE
Integrate AttributeCode to `attrib`

### ISSUE THREAD

**Issue by chinyeungli** [nexB/aboutcode-toolkit#479]
The attributecode has the ability to take csv/excel/json as an input to generate attribution. We should integrate this ability to `attrib`

**Comment by chinyeungli** [comment]
while integrating all the code and tests from attributecode to AbcTK. I figured out there are some conflicts.
For instance,
AbcTK use `license_expression` while the scan result from scancode tk uses `license_expressions` (plural)
In addition, AbcTK only accepts `AND`/`OR`/`WITH` in the license expression as a string while scancode tk return license expression as a list such as `[isc, mit]`
While I can draft some code to have these work and by-pass some restriction/rules in AbcTK just like in AttributeCode, but I'll like some feedback before I move on to this approach.

**Comment by mjherzog** [comment]
I think that we should update AbcTK to conform with SCTK as much as possible.

**Comment by chinyeungli** [comment]
okay.. I will use the `AND` condition for the scancode tk returned license_expressions
i.e. `[isc, mit]` will become `isc AND mit`

**Comment by chinyeungli** [comment]
This's fixed and pushed to the develop branch.
