### ISSUE TITLE
about attrib fails with duplicate about_resource

### ISSUE THREAD

**Issue by goneall** [nexB/aboutcode-toolkit#495]
When running `about attrib` with an XLSX or CSV file containing duplicate values in the `about_resource` column, the following error occurs:

`CRITICAL: The input has duplicated values in 'about_resource' field: ...`

In this scenario, the resource is a container image which has several identified packages which point to the same file.

Do I need to generate unique names for each field or can the ABCTK be changed to allow duplicate `about_resource` fields?

**Comment by chinyeungli** [comment]
The current design is a one to one relationship. i.e one ABOUT file reference one resource. Therefore, no duplicate `about_resource` is allowed. However, there is also a scenario that we are generating attribution directly from an inventory without creating ABOUT files, the restriction or limitation maybe too harsh.

**Comment by mjherzog** [comment]
We need to remove this restriction if you are not creating ABOUT files.
