### ISSUE TITLE
Why the limitation to ASCII in ABOUT file spec?

### ISSUE THREAD

**Issue by silverhook** [nexB/aboutcode-toolkit#519]
I just noticed that the [spec for the ABOUT file allows only ASCII in it](https://github.com/nexB/aboutcode-toolkit/blob/develop/docs/source/specification.rst#specification) and I wonder why that is.

Looking at the fields in it, I am certain at least the `copyright` field will include either the © sign or names with non-ASCII characters.

The `about_resource` field is also likely to end up covering a file that has non-ASCI characters in its name.

**Comment by chinyeungli** [comment]
The main intention is we want the ABOUT file to be a simple text document that all text editors supported. We could have unicode support, but it will create issues for editors that don't have unicode support or setup.

@pombredanne and @mjherzog any input on this?

**Comment by pombredanne** [comment]
There is no reason beyond historical issues to avoid complexities. This is no longer something that holds nowadays and we should accept UTF-8 encoded files alright. We need to update the spec accordingly.
