### ISSUE TITLE
missing curl dependency in Dockerfile

### ISSUE THREAD

**Issue by atoolchain** [nexB/aboutcode-toolkit#532]
hi nexB Team,
first of all, i like your scancode-toolkit and want to start using the aboutcode-toolkit.
I tried to build a docker image with version v10.0.0, v9.0.0, v8.0.0 & v7.2.0 and failed due to the lack of curl dependency in the build:

Step 6/7 : RUN bash -c "source ./configure"
./configure: line 102: curl: command not found
'/bin/sh -c bash -c "source ./configure"' returned a non-zero code: 127
...
in the line 12 (https://github.com/nexB/aboutcode-toolkit/blob/v10.0.0/Dockerfile#L12) curl should be added

it would be nice to dockerize your software to be able to use it in our pipelines.
I would be happy to hear from you again.
with best regards
alex

**Comment by pombredanne** [comment]
@atoolchain Thank you for the report and the kind words. Good catch!
