### ISSUE TITLE
Add numeric value support for 'attribute'

### ISSUE THREAD

**Issue by chinyeungli** [nexB/aboutcode-toolkit#543]
Some user/project may want numeric value instead of boolean value for 'attribute', so the tool has to support both

**Comment by DennisClark** [comment]
@chinyeungli   Actually I think it would be better to support a character value, which could of course possibly have a value that happens to be a number, but a character makes more sense for something that would not be used for any calculations.

**Comment by chinyeungli** [comment]
@DennisClark do you mean to support Boolean + Integer + Character as some people may use double digits for the 'attribute' field such as 11, 15 etc...

**Comment by DennisClark** [comment]
I think Boolean + Character (2) should be sufficient

**Comment by chinyeungli** [comment]
okay, I can make that change.
