### ISSUE TITLE
Better description/reasoning for Optional boolean flags in ABOUT files

### ISSUE THREAD

**Issue by silverhook** [nexB/aboutcode-toolkit#549]
The `ABOUT` file spec currently describes `redistribute` and `track_changes` [Optional boolean flag fields](https://aboutcode.readthedocs.io/projects/aboutcode-toolkit/en/latest/specification.html#optional-boolean-flag-fields) in a way where it seems like it (entirely) depends on the license.

If that were so, those flags are obsolete, as the data is already in the `license_*` fields and it just needs parsing. (e.g. if `license_key: EUPL-1.2` then redistribute source code).

If that is not so, then those flags need better explanation. I imagine perhaps as an indication of an internal decision (and actual act) to redistribute source code and track changes respectively.

**Comment by mjherzog** [comment]
There is a third field in this group: `attribute` under [Optional Boolean and Character fields](https://aboutcode.readthedocs.io/projects/aboutcode-toolkit/en/latest/specification.html#optional-boolean-and-character-fields). Parsing the license text to determine whether attribution or redistribution applies would be complex and extremely slow when you are running ACTK or related tools to create compliance documents. An alternative approach might be to determine attribution or redistribution based on License Category from the LicenseDB, but there are still use cases where you might need a more nuanced determination of the obligation to attribute, redistribute or track changes (as you suggested).

**Comment by chinyeungli** [comment]
obsolete
