### ISSUE TITLE
Migrate https://github.com/nexB/aboutcode-toolkit to https://github.com/aboutcode-org/

### ISSUE THREAD

**Issue by pombredanne** [nexB/aboutcode-toolkit#559]

**Comment by chinyeungli** [comment]
@pombredanne I think you have to do it as I don't have the permission to do.

Under the `Danger Zone`
```
Transfer ownership
Organization members cannot transfer repositories
```

**Comment by chinyeungli** [comment]
Done with following instruction from https://github.com/aboutcode-org/matchcode-toolkit/issues/10#issuecomment-2121302473
