### ISSUE TITLE
Allow ABOUT file without an about_resource

### ISSUE THREAD

**Issue by pombredanne** [nexB/aboutcode-toolkit#562]
This is useful to track and curate packages independently of their locations.
Here the key would be the PURL.

**Comment by chinyeungli** [comment]
@pombredanne Can you provide me with a scenario or intention for this? Is the intention solely to verify the correctness of the license_expression? If that's the case, perhaps it would be more appropriate to have a subcommand, let's say validate_license_expression?

**Comment by pombredanne** [comment]
Say I have a large codebase, many many packages and that the actual location of a package on disk in the devel or deployed code may vary over time. I would like to keep ABOUT files that provide a proper, curated license and origin that is not specific to any given location, but just for a purl.

Then when a scanner finds a PURL, we can have a process to use the ABOUT file data to supplement the data.

**Comment by chinyeungli** [comment]
Here is the proposed update:
 * Make the `about_resource` field as a non-requirement field
 * Introduce an new option in `gen`, let say `--output_dir`, to dump all the created ABOUT files into it. If `about_resource` field does not present or if there is empty value for `about_resource`, the tool will prompt an error and ask either correct the input or to use the `--output_dir` option

**Comment by chinyeungli** [comment]
Fixed without the above proposed solution. Instead, the tool will generate the ABOUT files in the declared output location if no `about_resource` is provided.
