### ISSUE TITLE
dockerfile entrypoint is broken

### ISSUE THREAD

**Issue by atoolchain** [nexB/aboutcode-toolkit#571]
hi aboutcode Team,
i just checked out the tag v11.0.0 and tried to build and run the docker image.
the build went just fine but when i try run it with:
`docker run --rm test-aboutcode-toolkit --version`
to basically do a:
`./about --version`
i get the error message:
> docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./bin/about": stat ./bin/about: no such file or directory: unknown.

i think the entrypoint in the Dockerfile should be "./about" and not "./bin/about"

with best regards
alex

**Comment by chinyeungli** [comment]
Thanks for catching this.
