### ISSUE TITLE
missing (pip) requests module in Docker Image

### ISSUE THREAD

**Issue by atoolchain** [nexB/aboutcode-toolkit#572]
hi aboutcode Team,
i just checked out the tag v11.0.0 and tried to build and run the docker image.
the build went just fine, for the docker run there is an issue i found with the [broken entrypoint](https://github.com/aboutcode-org/aboutcode-toolkit/issues/571).
if i do a workaround with:
`docker run --rm --entrypoint './about' test-aboutcode-toolkit --version`
to do a simple `./about --version` 
i get a python Traceback:

> Traceback (most recent call last):
  File "/aboutcode-toolkit/venv/bin/about", line 5, in <module>
    from attributecode.cmd import about
  File "/aboutcode-toolkit/src/attributecode/cmd.py", line 29, in <module>
    from attributecode.model import write_output
  File "/aboutcode-toolkit/src/attributecode/model.py", line 30, in <module>
    from requests import get, head, exceptions
ModuleNotFoundError: No module named 'requests'

if i run the container with `docker run --rm --entrypoint '' -d test-aboutcode-toolkit sleep 1h`
and "go" into the container with `docker exec -it 66531063cb81 bash`,
i can install the requests module, and its dependencies, into the virtualenv by: `./venv/bin/pip install requests`
than i get the right output from the ./about --version

it would be nice if you could add the dependencies into the virtualenv :)

with best regards
alex

**Comment by chinyeungli** [comment]
Added the requests package: https://github.com/aboutcode-org/aboutcode-toolkit/blob/develop/setup.cfg#L69
