### ISSUE TITLE
Need to add autoescaping for the template engine 

### ISSUE THREAD

**Issue by chinyeungli** [nexB/aboutcode-toolkit#91]
for the unlicense
https://enterprise.dejacode.com/license_library/nexB/unlicense/#license-text

the template seems fail to get the the last segment is "http://unlicense.org/"

i.e. the last line of the generated attribution output is

For more information, please refer to 

instead of

For more information, please refer to http://unlicense.org/

I checked the about.py and confirm the it passes the complete license_text to the template, but somehow, the template doesn't display the url.. perhaps because of the '<' 

[2:59:05 PM] Thomas Druez: I think you're right, the template engine is probably handling the http://unlicense.org/ as an HTML element because of the <>

See http://jinja.pocoo.org/docs/api/#autoescaping

**Comment by jdaguil** [comment]
Based on http://jinja.pocoo.org/docs/templates/#html-escaping 
Escaping works by piping the variable through the |e filter

**Comment by chinyeungli** [comment]
Thanks Jillian
