### ISSUE TITLE
Authorization denied when trying to fetch licenses through DejaCode Enterprise

### ISSUE THREAD

**Issue by jdaguil** [nexB/aboutcode-toolkit#95]
When trying to generate about files while using the --extract_license option, the following Error occurs: 

Authorization denied. Invalid '--api_username' or '--api_key'. LICENSE generation is skipped.

The about files are generated but the licenses are not created via the DejaCode API.

**Comment by chinyeungli** [comment]
please try it with the latest code

**Comment by jdaguil** [comment]
it's fixed thanks!
