### ISSUE TITLE
Handling of fields based on upper or lower case characters

### ISSUE THREAD

**Issue by jdaguil** [nexB/aboutcode-toolkit#97]
When trying to generate an about file from a .csv file, an optional field was ignored based on it's case. 
For example, Copyright was not created as a field in the about file because of the capital 'C'. It's a subtle case, and we do have a warning in the log that it was ignored. But should we accept an optional field name regardless of the case?

**Comment by jdaguil** [comment]
@chinyeungli what do you think?

**Comment by chinyeungli** [comment]
@jdaguil I think it should be case in-sensitive. Do you want me to fix it, or you think you can handle it?
